services:
  postgres:
    image: postgres:16
    container_name: asocial_db
    environment:
      POSTGRES_USER: asocial
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asocial
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
